pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'ap-south-1'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/suren00-77-99/lambda-project.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Destroy Infrastructure') {
            steps {
                input message: 'Confirm Terraform Destroy'

                dir('Terraform') {
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
    }

    post {
        success {
            echo 'Infrastructure destroyed successfully.'
        }

        always {
            cleanWs()
        }
    }
}